data:
  source:
    path:
      dev: data/image/dev
      test: data/image/test
      train: data/image/train
  hog:
    path:
      dev: data/hog/dev
      test: data/hog/test
      train: data/hog/train

