preprocess:
  source:
    path:
      dev: data/image/dev
      test: data/image/test
      train: data/image/train
  hog:
    path:
      dev: data/hog/dev
      test: data/hog/test
      train: data/hog/train
    channels:
      - [1, 2, 3]
      - [6, 7, 8]
      - [11, 12, 13]
model:
  hog:
    dev:
      data: data/hog/dev/hog.npy
      labels: data/hog/dev/labels.npy
    test:
      data: data/hog/test/hog.npy
      labels: data/hog/test/labels.npy
    train:
      data: data/hog/train/hog.npy
      labels: data/hog/train/labels.npy



